name: diabetes_project
channels:
  - anaconda
  - defaults
dependencies:
  - backcall=0.2.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - colorama=0.4.4
  - decorator=4.4.2
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - libsodium=1.0.18
  - openssl=1.1.1k
  - parso=0.8.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - prompt-toolkit=3.0.8
  - pygments=2.7.1
  - python=3.8.11
  - pywin32=227
  - pyzmq=19.0.2
  - setuptools=52.0.0
  - sqlite=3.36.0
  - traitlets=5.0.5
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.37.0
  - wincertstore=0.2
  - zeromq=4.3.2
  - pip:
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==21.2.0
    - bleach==4.0.0
    - cffi==1.14.6
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - defusedxml==0.7.1
    - entrypoints==0.3
    - ipywidgets==7.6.3
    - jinja2==3.0.1
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-console==6.4.0
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - llvmlite==0.36.0
    - lxml==4.6.3
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.3
    - numba==0.53.1
    - packaging==21.0
    - pandas==1.3.1
    - pandocfilters==1.4.3
    - pillow==8.3.1
    - prometheus-client==0.11.0
    - pycparser==2.20
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pywinpty==1.1.3
    - pyyaml==5.4.1
    - qtconsole==5.1.1
    - qtpy==1.9.0
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - seaborn==0.11.1
    - send2trash==1.8.0
    - shap==0.39.0
    - six==1.16.0
    - slicer==0.0.7
    - terminado==0.11.0
    - testpath==0.5.0
    - threadpoolctl==2.2.0
    - tornado==6.1
    - tqdm==4.62.1
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
